name: gapless_audio_loop
description: A plugin specialized on playing audio files on a gapless loop
version: 1.1.0
author: Erick Zanardo <erick@fireslime.xyz>
homepage: https://github.com/fireslime/flutter_gapless_audio_loop

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: xyz.fireslime.gapless_audio_loop
    pluginClass: GaplessAudioLoopPlugin
